### ISSUE TITLE
☂️ 22.Q3 Check Tarantool installation on all platforms

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/delivery-checker#52]
# Check installation on all platforms and retry individual checks

## Core (CLI, logging, test management)

- [ ] https://github.com/tarantool/delivery-checker/issues/45
- [ ] Print logs to stdout and/or files

## Additional check targets

- [x] #53
  - [ ] https://github.com/tarantool/actions/issues/3

## Additional checks

- [ ] Check for installed package's architecture (?)
- [ ] Check that rocks can be installed with `tarantoolctl`
- [ ] #56

## Extra tooling

- [ ] https://github.com/tarantool/delivery-checker/issues/54
- [x] https://github.com/tarantool/delivery-checker/issues/34
- [ ] https://github.com/tarantool/delivery-checker/issues/37

**Comment by NickVolynkin** [comment]
Outdated, superceded by https://github.com/tarantool/delivery-checker/issues/58
